version: v3

services:
  server:
    container_name: "server"
    restart: on-failure
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
      - "6379:6379"
      - "27017:27017"
    environment:
      # Logger
      - LEVEL

      # Server
      - SERVERADDR

      # Redis
      - REDISADDR

      # MongoDB
      - URI