apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: servre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: app
        image: blog/server
        ports:
        - containerPort: 8080
        env:
          - name: LEVEL
            value: "info"
          - name: HOST
            value: "blog"
          - name: PORT
            value: "8080"