FROM golang:alpine

# RUN apk update && apk add git

ENV BIN_FILE /server
ENV CODE_DIR /go/src/

WORKDIR ${CODE_DIR}

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build \
        -o ${BIN_FILE} ./cmd/web/*

EXPOSE 8080

CMD ${BIN_FILE}